CREATE TABLE BOOK
(
BookId INT NOT NULL PRIMARY KEY, 
Title varchar(255),
PublisherName varchar(255)
)

CREATE TABLE PUBLISHER
(
Name VARCHAR(255) NOT NULL PRIMARY KEY, 
Address VARCHAR(255),
Phone VARCHAR(20)
)

CREATE TABLE BOOK_AUTHORS
(
BookId INT NOT NULL PRIMARY KEY,
AuthorName VARCHAR(255)NOT NULL
)

CREATE TABLE BOOK_COPIES
(
BookId INT NOT NULL PRIMARY KEY,
BranchId INT NOT NULL,
No_Of_Copies INT
)

CREATE TABLE BOOK_LOANS
(
BookId INT NOT NULL PRIMARY KEY,
BranchId INT NOT NULL,
CardNo INT NOT NULL,
DateOut DATE,
DueDate DATE
)

CREATE TABLE LIBRARY_BRANCH
(
Branch_Id INT NOT NULL PRIMARY KEY,
BranchName VARCHAR(255),
Address VARCHAR(255)
)

CREATE TABLE BORROWER
(
CardNo INT NOT NULL PRIMARY KEY,
Name VARCHAR(255),
Address VARCHAR(255),
Phone VARCHAR(255)
)